.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. blackmore_qt test_blackmore_qt
clean: FORCE
	$(MAKE) -C .. blackmore_qt_clean test_blackmore_qt_clean
check: FORCE
	$(MAKE) -C .. test_blackmore_qt_check
blackmore-qt blackmore-qt.exe: FORCE
	 $(MAKE) -C .. blackmore_qt
