name: Build and Push Docker - master
on: [push]
jobs:
  test:
    name: Build and Push Docker - master
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: BlackcoinDev/docker-blk
          ref: main
      - name: Set environment variables
        run: echo "GIT_CURRENT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Show GITHUB_ENV content
        run: cat $GITHUB_ENV
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Run build script
        run: ./gh-build-26.sh