FROM ubuntu AS ubase-base-arm-linux-gnueabihf
ARG BRANCH
ENV BRANCH=$BRANCH
ARG TIMEZONE
ENV TIMEZONE=$TZ
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -yqq \
                          git \ 
                          make \
                          file \
                          autoconf \
                          automake \ 
                          libtool \
                          libevent-dev \
                          build-essential \
                          autotools-dev \
                          pkg-config \
                          bsdmainutils \
                          python3 \
                          libevent-dev \
                          libboost-all-dev \
                          libminiupnpc-dev \
                          libzmq3-dev \
                          libssl-dev \
                          gperf \
                          wget \
# blk commandline utility 
                          jq \
                          bc \ 
# cross compile arm
                          g++-arm-linux-gnueabihf  \ 
                          binutils-arm-linux-gnueabihf \ 
# cross compile aarch64
                          g++-aarch64-linux-gnu  \ 
                          binutils-aarch64-linux-gnu \ 
# cross compile macOS
                          curl  \ 
                          librsvg2-bin  \ 
                          libtiff-tools  \ 
                          bsdmainutils  \ 
                          cmake  \ 
                          imagemagick  \ 
                          libcap-dev  \ 
                          libz-dev  \ 
                          libbz2-dev  \ 
                          python3-setuptools  \ 
                          libtinfo5 

FROM ubase-base-arm-linux-gnueabihf AS ubase-arm-linux-gnueabihf

RUN git clone -b $BRANCH https://github.com/CoinBlack/blackcoin-more.git

COPY arm-linux-gnueabihf ./arm-linux-gnueabihf
WORKDIR /blackcoin-more
RUN (git clean -xf && \
      ./autogen.sh && \
      ./configure --prefix=/arm-linux-gnueabihf --enable-glibc-back-compat --enable-reduce-exports --disable-tests --disable-bench --disable-gui-tests --enable-upnp-default LDFLAGS=-static-libstdc++ && \
      make -j4  && \
      make install && \
      cd src/ && \
      /usr/bin/arm-linux-gnueabihf-strip blackmore*)

RUN cp /blackcoin-more/src/blackmored /usr/local/bin/ && \
  cp /blackcoin-more/src/blackmore-cli /usr/local/bin/ && \
  cp /blackcoin-more/contrib/blk /usr/local/bin/
WORKDIR /arm-linux-gnueabihf/parts
RUN cp --parents /usr/local/bin/blk ./ && \
  cp --parents /usr/local/bin/blackmored ./ && \
  for i in `ldd /usr/local/bin/blackmored | grep -v linux-vdso.so.1 | awk {' if ( $3 == "") print $1; else print $3 '}`; do cp --parents $i ./; done && \
  cp --parents /usr/local/bin/blackmore-cli ./ && \
  for i in `ldd /usr/local/bin/blackmore-cli | grep -v linux-vdso.so.1 | awk {' if ( $3 == "") print $1; else print $3 '}`; do cp --parents $i ./; done && \
  cp /usr/bin/bc --parents ./ && \
  cp /usr/bin/jq --parents ./
WORKDIR /